worker_processes auto;
  pid /tmp/nginx.pid;

  events {
    worker_connections 1024;
  }

  http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
      listen ${PORT};
      server_name localhost;
      root /workspace;
      index index.html;
  
      location /api/ {
        proxy_pass http://${API_URL}/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
  
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
  }